UD_Granit/Models/Dissertation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace UD_Granit.Models
{
    public enum DissertationType : short
    {
        [Description("Кандидатская")]
        Candidate = 0,
        [Description("Докторская")]
        Doctor = 1
    }

    public class Dissertation
    {
        [Key]
        public int Id { set; get; }

        [Required]
        [Display(Name = "Тип диссертационной работы")]
        public DissertationType Type { set; get; }

        [Display(Name = "Диссертация защищена")]
        public bool Defensed { set; get; }

        [Required]
        [Display(Name = "Заголовок")]
        public string Title { set; get; }

        [Required]
        [Display(Name = "Автореферат")]
        public string File_Abstract { set; get; }

        [Required]
        [Display(Name = "Текст диссертации")]
        public string File_Text { set; get; }

        [Required]
        [Display(Name = "Заключение ведущей организации")]
        public string File_Summary { set; get; }

        [Display(Name = "Список литературы")]
        public string References { set; get; }

        [Required]
        [Display(Name = "Для внутреннего использования")]
        public bool Administrative_Use { set; get; }

        [Required]
        [Display(Name = "Число ВАКовских публикаций")]
        public int Publications { set; get; }

        [Display(Name = "Дата последней публикации")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? Date_Sending { set; get; }

        [Display(Name = "Дата предварительной защиты")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? Date_Preliminary_Defense { set; get; }

        public virtual ICollection<Reply> Replies { set; get; }
        public virtual ICollection<Session> Sessions { set; get; }

        [Required]
        [Display(Name = "Специальность")]
        public virtual Speciality Speciality { set; get; }

        [Required]
        public virtual Applicant Applicant { set; get; }
    }
}

UD_Granit/ViewModels/Account/Delete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Account
{
    public class Delete
    {
        public int Id { set; get; }
        public string Name { set; get; }
        public string Referer { set; get; }
        public bool CanDelete { set; get; }
    }
}

UD_Granit/ViewModels/Account/Details.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Account
{
    public class ApplicantViewItem
    {
        [Display(Name = "Город")]
        public string City { set; get; }

        [Display(Name = "Организация")]
        public string Organization { set; get; }

        [Display(Name = "Подразделение")]
        public string Organization_Depatment { set; get; }
    }

    public class MemberViewItem
    {
        [Display(Name = "Должность")]
        public string Position { set; get; }

        [Display(Name = "Специальность")]
        public UD_Granit.Models.Speciality Speciality { set; get; }
    }

    public class Details
    {
        public int User_Id { set; get; }

        [Display(Name = "Полное имя")]
        public string FullName { set; get; }

        [Display(Name = "Роль")]
        public string Role { set; get; }

        public ApplicantViewItem ApplicantView { set; get; }
        public MemberViewItem MemberView { set; get; }

        public bool CanControl { set; get; }
    }
}

UD_Granit/ViewModels/Account/Edit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Account
{
    public class Edit
    {
        public int Id { set; get; }

        [Required]
        [Display(Name = "Ваш текущий пароль")]
        public string OldPassword { set; get; }

        [Display(Name = "Новый пароль")]
        public string NewPassword { set; get; }

        [Required]
        [Display(Name = "Фамилия")]
        public string FirstName { set; get; }

        [Required]
        [Display(Name = "Имя")]
        public string SecondName { set; get; }

        [Display(Name = "Отчество")]
        public string LastName { set; get; }
    }
}

UD_Granit/ViewModels/Council/Edit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Council
{
    public class Edit
    {
        public UD_Granit.Models.Council Council { set; get; }

        public ICollection<System.Web.Mvc.SelectListItem> Members { set; get; }
        public bool CanDefineRoles { set; get; }
        public bool CanDefineChairman { set; get; }

        [Display(Name="Председатель совета")]
        public int Chairman { set; get; }

        [Display(Name = "Заместитель председателя")]
        public int ViceChairman { set; get; }

        [Display(Name = "Учёный секретарь")]
        public int Secretary { set; get; }
    }
}

UD_Granit/ViewModels/Dissertation/Delete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Dissertation
{
    public class Delete
    {
        public int Id { set; get; }
        public string Title { set; get; }
        public bool CanDelete { set; get; }
    }
}

UD_Granit/Controllers/DissertationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UD_Granit.Models;
using UD_Granit.Helpers;
using System.IO;
using System.Data.SqlClient;

namespace UD_Granit.Controllers
{
    // Управляет логикой по работе с диссертациями
    public class DissertationController : Controller
    {
        private DataContext db = new DataContext();

        // Отображает список диссертаций
        // GET: /Dissertation/

        public ActionResult Index(string search)
        {
            UD_Granit.ViewModels.Dissertation.Index viewModel = new ViewModels.Dissertation.Index();
            viewModel.Dissertations = new List<Dissertation>();

            IEnumerable<Dissertation> dissertations = null;

            if ((search != null) && (search.Length > 0))
            {
                viewModel.SearchHaveResults = true;
                viewModel.SearchString = search;
                dissertations = db.Database.SqlQuery<Dissertation>("FindDissertations @phrase", new SqlParameter("phrase", search));
            }
            else
            {
                dissertations = db.Database.SqlQuery<Dissertation>("GetDissertations");
            }

            foreach (var currentDissertation in dissertations)
            {
                if (RightsManager.Dissertation.Show(Session.GetUser(), currentDissertation))
                {
                    viewModel.Dissertations.Add(db.Dissertations.Find(currentDissertation.Id));
                }
            }
            return View(viewModel);
        }

        // Показывает подробности о диссертации
        // GET: /Dissertation/Details/5

        public ActionResult Details(int id)
        {
            Dissertation dissertation = db.Dissertations.Find(id);
            if (RightsManager.Dissertation.Show(Session.GetUser(), dissertation))
            {
                UD_Granit.ViewModels.Dissertation.Details viewModel = new ViewModels.Dissertation.Details();
                viewModel.Dissertation = dissertation;

                User currentUser = Session.GetUser();
                viewModel.CanEdit = RightsManager.Dissertation.Edit(currentUser, dissertation) && (dissertation.Sessions.Count() == 0);
                viewModel.CanCreateSession = RightsManager.Session.Create(currentUser);
                viewModel.CanAddReplies = RightsManager.Reply.Control(currentUser, dissertation);
                viewModel.CanEditReplies = RightsManager.Reply.Control(currentUser, dissertation);

                return View(viewModel);
            }
            throw new HttpException(404, "Not found");
        }

        // Показывает форму создания диссертации
        // GET: /Dissertation/Create

        public ActionResult Create()
        {
            if (Session.GetUser() != null)
            {
                User currentUser = Session.GetUser();
                if (currentUser is Applicant)
                {
                    var dissertations = db.Dissertations.Where(d => d.Applicant.Id == currentUser.Id);
                    if (dissertations.Count() == 0)
                    {
                        ViewData.NotificationAdd(new NotificationManager.Notify() { Type = NotificationManager.Notify.NotifyType.Info, Message = "Заполните информацию о Вашей диссертации. Вы можете сделать это позже, также как и отредактировать информацию о ней." });
                        ViewData["Speciality"] = db.Specialities.Select(s => new SelectListItem { Text = s.Number + " " + s.Name, Value = s.Number });

                        return View();
                    }
                    else
                    {
                        return RedirectToAction("Details", new { id = dissertations.Single().Id });
                    }
                }
            }
            throw new HttpException(404, "Not found");
        }

        // Создаёт запись о диссертации
        // POST: /Dissertation/Create

        [HttpPost]
        public ActionResult Create(UD_Granit.ViewModels.Dissertation.Create viewModel)
        {
            Applicant currentUser = Session.GetUser() as Applicant;

            if (currentUser == null)
                throw new HttpException(404, "Not found");

            if (db.Dissertations.Where(d => d.Applicant.Id == currentUser.Id).Count() != 0)
                throw new HttpException(404, "Not found");

            Dissertation currentDissertation = viewModel.Dissertation;
            currentDissertation.Type = (currentUser is ApplicantCandidate) ? DissertationType.Candidate : DissertationType.Doctor;
            currentDissertation.Applicant = db.Applicants.Find(currentUser.Id);
            currentDissertation.File_Abstract = Path.GetExtension(viewModel.File_Abstract.FileName);
            currentDissertation.File_Text = Path.GetExtension(viewModel.File_Text.FileName);
            currentDissertation.File_Summary = Path.GetExtension(viewModel.File_Summary.FileName);
            currentDissertation.Defensed = false;
            currentDissertation.Speciality = db.Specialities.Find(viewModel.Speciality);

            db.Dissertations.Add(currentDissertation);
            db.SaveChanges();

            viewModel.File_Abstract.SaveAs(Server.MapPath(Path.Combine("~/App_Data/", currentDissertation.Id + "_Abstract" + currentDissertation.File_Abstract)));
            viewModel.File_Text.SaveAs(Server.MapPath(Path.Combine("~/App_Data/", currentDissertation.Id + "_Text" + currentDissertation.File_Text)));
            viewModel.File_Summary.SaveAs(Server.MapPath(Path.Combine("~/App_Data/", currentDissertation.Id + "_Summary" + currentDissertation.File_Summary)));

            return RedirectToAction("Details", new { id = currentDissertation.Id });
        }

        // Показывает форму редактирования диссертации
        // GET: /Dissertation/Edit/5

        public ActionResult Edit(int id)
        {
            User currentUser = Session.GetUser();
            Dissertation currentDissertation = db.Dissertations.Find(id);

            if (currentDissertation == null)
                throw new HttpException(404, "Not found");

            if (!RightsManager.Dissertation.Edit(currentUser, currentDissertation))
                throw new HttpException(404, "Not found");

            if (currentDissertation.Sessions.Count() > 0)
                throw new HttpException(404, "Not found");

            UD_Granit.ViewModels.Dissertation.Edit viewModel = new ViewModels.Dissertation.Edit();
            viewModel.Dissertation = currentDissertation;

            ViewData["Speciality"] = db.Specialities.Select(s => new SelectListItem { Text = s.Number + " " + s.Name, Value = s.Number });
            return View(viewModel);
        }

        // Редактирует запись о диссертации
        // POST: /Dissertation/Edit/5

        [HttpPost]
        public ActionResult Edit(UD_Granit.ViewModels.Dissertation.Edit viewModel)
        {
            try
            {
                Dissertation currentDissertation = viewModel.Dissertation;
                currentDissertation.Speciality = db.Specialities.Find(viewModel.Speciality);

                Dissertation baseDissertation = db.Dissertations.Find(currentDissertation.Id);

                baseDissertation.Title = currentDissertation.Title;
                baseDissertation.Publications = currentDissertation.Publications;
                baseDissertation.Administrative_Use = currentDissertation.Administrative_Use;
                baseDissertation.Date_Preliminary_Defense = currentDissertation.Date_Preliminary_Defense;
                baseDissertation.Date_Sending = currentDissertation.Date_Sending;
                baseDissertation.Defensed = currentDissertation.Defensed;
                baseDissertation.References = currentDissertation.References;

                baseDissertation.Speciality = currentDissertation.Speciality;
                baseDissertation.Applicant = db.Applicants.Find(Session.GetUser().Id);

                if (viewModel.File_Abstract != null)
                {
                    System.IO.File.Delete(Server.MapPath(Path.Combine("~/App_Data/", currentDissertation.Id + "_Abstract" + baseDissertation.File_Abstract)));
                    baseDissertation.File_Abstract = Path.GetExtension(viewModel.File_Abstract.FileName);
                    viewModel.File_Abstract.SaveAs(Server.MapPath(Path.Combine("~/App_Data/", currentDissertation.Id + "_Abstract" + baseDissertation.File_Abstract)));
                }
                if (viewModel.File_Text != null)
                {
                    System.IO.File.Delete(Server.MapPath(Path.Combine("~/App_Data/", currentDissertation.Id + "_Text" + baseDissertation.File_Text)));
                    baseDissertation.File_Text = Path.GetExtension(viewModel.File_Text.FileName);
                    viewModel.File_Text.SaveAs(Server.MapPath(Path.Combine("~/App_Data/", currentDissertation.Id + "_Text" + baseDissertation.File_Text)));
                }
                if (viewModel.File_Summary != null)
                {
                    System.IO.File.Delete(Server.MapPath(Path.Combine("~/App_Data/", currentDissertation.Id + "_Summary" + baseDissertation.File_Summary)));
                    baseDissertation.File_Summary = Path.GetExtension(viewModel.File_Summary.FileName);
                    viewModel.File_Summary.SaveAs(Server.MapPath(Path.Combine("~/App_Data/", currentDissertation.Id + "_Summary" + baseDissertation.File_Summary)));
                }

                db.Entry<Dissertation>(baseDissertation).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();

                return RedirectToAction("Details", new { id = currentDissertation.Id });
            }
            catch (Exception ex)
            {
                ViewData["Speciality"] = db.Specialities.Select(s => new SelectListItem { Text = s.Number + " " + s.Name, Value = s.Number });

UD_Granit/Controllers/ReplyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UD_Granit.Helpers;
using UD_Granit.Models;

namespace UD_Granit.Controllers
{
    // Управляет логикой по работе с отзывами
    public class ReplyController : Controller
    {
        private DataContext db = new DataContext();

        // Показывает форму добавления отзыва
        // GET: /Reply/Create/5

        public ActionResult Create(int id)
        {
            Dissertation dissertation = db.Dissertations.Find(id);
            if (!RightsManager.Reply.Control(Session.GetUser(), dissertation))
                throw new HttpException(404, "Not found");

            UD_Granit.ViewModels.Reply.Create viewModel = new ViewModels.Reply.Create();
            viewModel.Dissertation_Id = dissertation.Id;

            return View(viewModel);
        }

        // Создаёт отзыв к диссертации
        // POST: /Reply/Create/5

        [HttpPost]
        public ActionResult Create(ViewModels.Reply.Create viewModel)
        {
            Dissertation dissertation = db.Dissertations.Find(viewModel.Dissertation_Id);
            if (!RightsManager.Reply.Control(Session.GetUser(), dissertation))
                throw new HttpException(404, "Not found");

            Reply currentReply = viewModel.Reply;
            currentReply.Dissertation = dissertation;
            db.Replies.Add(currentReply);
            db.SaveChanges();

            return RedirectToAction("Details", "Dissertation", new { id = dissertation.Id });
        }

        // Удаляет отзыв к диссертации
        // GET: /Reply/Delete/5

        public ActionResult Delete(int id)
        {
            Reply currentReply = db.Replies.Find(id);
            Dissertation currentDissertation = currentReply.Dissertation;

            if (!RightsManager.Reply.Control(Session.GetUser(), currentDissertation))
                throw new HttpException(404, "Not found");

            db.Replies.Remove(currentReply);
            db.SaveChanges();
            return RedirectToAction("Details", "Dissertation", new { id = currentDissertation.Id });
        }
    }
}

UD_Granit/Views/Dissertation/Create.cshtml
@model UD_Granit.ViewModels.Dissertation.Create

@{
    ViewBag.Title = "Новая диссертация";
}

<h2>Создать запись о диссертации</h2>
<p>На этой странице Вы должны заполнить информацию о Вашей диссертации. Записи о диссертациях, в которые будет занесена неверная информация, будут удалены из системы.</p>

@using (Html.BeginForm("Create", "Dissertation", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Основная информация о диссертации</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Dissertation.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Dissertation.Title)
            @Html.ValidationMessageFor(model => model.Dissertation.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Speciality)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Speciality, null)
            @Html.ValidationMessageFor(model => model.Speciality)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Dissertation.Publications)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Dissertation.Publications)
            @Html.ValidationMessageFor(model => model.Dissertation.Publications)
        </div>
    </fieldset>
    
    <fieldset>
        <legend>Прикрепляемые файлы</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.File_Abstract)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.File_Abstract, new { type = "file" })
            @Html.ValidationMessageFor(model => model.File_Abstract)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.File_Text)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.File_Text, new { type = "file" })
            @Html.ValidationMessageFor(model => model.File_Text)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.File_Summary)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.File_Summary, new { type = "file" })
            @Html.ValidationMessageFor(model => model.File_Summary)
        </div>
    </fieldset>
    
    <fieldset>
        <legend>Дополнительная информация о диссертации</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Dissertation.References)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Dissertation.References)
            @Html.ValidationMessageFor(model => model.Dissertation.References)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Dissertation.Administrative_Use)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Dissertation.Administrative_Use)
            @Html.ValidationMessageFor(model => model.Dissertation.Administrative_Use)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.Dissertation.Date_Sending)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Dissertation.Date_Sending)
            @Html.ValidationMessageFor(model => model.Dissertation.Date_Sending)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Dissertation.Date_Preliminary_Defense)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Dissertation.Date_Preliminary_Defense)
            @Html.ValidationMessageFor(model => model.Dissertation.Date_Preliminary_Defense)
        </div>
    </fieldset>

    <div class="control">
        <button>Добавить запись о диссертации</button>
    </div>
}

@section scripts {
	<script>
		$(function () {
			$("#Dissertation_Date_Sending").appendDtpicker({ locale: "ru", dateOnly: true, closeOnSelected: true, firstDayOfWeek: 1 });
			$("#Dissertation_Date_Preliminary_Defense").appendDtpicker({ locale: "ru", dateOnly: true, closeOnSelected: true, firstDayOfWeek: 1 });
		});
	</script>
}

UD_Granit/Views/Dissertation/Delete.cshtml
@model UD_Granit.ViewModels.Dissertation.Delete

@{
    ViewBag.Title = "Удаление диссертации";
}

<h2>Удаление записи о диссертации</h2>

@using (Html.BeginForm("Delete", "Dissertation"))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)

    if (Model.CanDelete)
    {
    <p>Вы действительно хотите удалить запись о диссертации <b>@Model.Title</b>?</p>
    
    <div class="control">
        <button>Да</button>
        @Html.ActionLink("Отмена", "Details", new { Id = Model.Id })
    </div>
    }
    else
    {
    <p>Извините, возникли ошибки при разборе логической целостности базы данных. Возможно, существуют заседания, связанные с этой диссертацией. Удаление невозможно.</p>
    
    <div class="control">
        @Html.ActionLink("Отмена", "Details", new { Id = Model.Id })
    </div>
    }
}

UD_Granit/Views/Dissertation/Details.cshtml
@model UD_Granit.ViewModels.Dissertation.Details

@{
    ViewBag.Title = "Подробности диссертации";
}

<h2>Подробная информация о диссертации</h2>
<h3>Сведения о диссертации</h3>
<table>
    <tbody>
        <tr>
            <td>@Html.LabelFor(model => model.Dissertation.Title)</td>
            <td>@Model.Dissertation.Title</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Dissertation.Publications)</td>
            <td>@Model.Dissertation.Publications</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Dissertation.Speciality)</td>
            <td>@Model.Dissertation.Speciality.Number @Model.Dissertation.Speciality.Name</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Dissertation.Type)</td>
            <td>@Model.Dissertation.Type.ToDescription()</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Dissertation.Defensed)</td>
            <td>@((Model.Dissertation.Defensed) ? "Да" : "Нет")</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Dissertation.Administrative_Use)</td>
            <td>@((Model.Dissertation.Administrative_Use) ? "Да" : "Нет")</td>
        </tr>
        @if (Model.Dissertation.References != null)
        {
            <tr>
                <td>@Html.LabelFor(model => model.Dissertation.References)</td>
                <td>
                    <pre>@Model.Dissertation.References</pre>
                </td>
            </tr>
        }
        @if (Model.Dissertation.Date_Sending != null)
        {
            <tr>
                <td>@Html.LabelFor(model => model.Dissertation.Date_Sending)</td>
                <td>@Html.DisplayFor(model => model.Dissertation.Date_Sending)</td>
            </tr>
        }
        @if (Model.Dissertation.Date_Preliminary_Defense != null)
        {
            <tr>
                <td>@Html.LabelFor(model => model.Dissertation.Date_Preliminary_Defense)</td>
                <td>@Html.DisplayFor(model => model.Dissertation.Date_Preliminary_Defense)</td>
            </tr>
        }
        <tr>
            <td>@Html.LabelFor(model => model.Dissertation.File_Abstract)</td>
            <td>@Html.ActionLink("Скачать", "Download", new { id = Model.Dissertation.Id, type = "Abstract" })</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Dissertation.File_Text)</td>
            <td>@Html.ActionLink("Скачать", "Download", new { id = Model.Dissertation.Id, type = "Text" })</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(model => model.Dissertation.File_Summary)</td>
            <td>@Html.ActionLink("Скачать", "Download", new { id = Model.Dissertation.Id, type = "Summary" })</td>
        </tr>

        <!--<tr>
            <td></td>
            <td></td>
        </tr>-->
    </tbody>
</table>

<h3>Сведения об отзывах</h3>
@if ((Model.Dissertation.Replies != null) && (Model.Dissertation.Replies.Count > 0))
{
    foreach (UD_Granit.Models.Reply reply in Model.Dissertation.Replies)
    {
    <table>
        <tbody>
            <tr>
                <td>Автор отзыва</td>
                <td>@reply.Author</td>
            </tr>
            <tr>
                <td>Организация (университет)</td>
                <td>@reply.Organization</td>
            </tr>
            <tr>
                <td>Подразделение (кафедра)</td>
                <td>@reply.Departmant</td>
            </tr>
            <tr>
                <td>Учёная степень</td>
                <td>@reply.Degree</td>
            </tr>
            <tr>
                <td colspan="2">Текст отзыва</td>
            </tr>
            <tr>
                <td colspan="2">
                    <pre>@reply.Text</pre>
                </td>
            </tr>
            @if (Model.CanAddReplies)
            {
                <tr>
                    <td>Управление</td>
                    <td>
                        @Html.ActionLink("Удалить", "Delete", "Reply", new { id = reply.Id }, null)
                    </td>
                </tr>   
            }
        </tbody>
    </table>
    <p></p>
    }
}
else
{
    <div class="error">Сведения об отзывах ещё не добавлены соискателем.</div>
}

<div class="control">
    @if (Model.CanEdit)
    {
        @Html.ActionLink("Редактировать", "Edit", new { id = Model.Dissertation.Id }) 
        @Html.ActionLink("Удалить", "Delete", new { id = Model.Dissertation.Id })
    }
    @if (Model.CanCreateSession)
    {
        @Html.ActionLink("Создать заседание по рассмотрению", "CreateConsideration", "Session", new { id = Model.Dissertation.Id }, null)
        @Html.ActionLink("Создать заседание по защите", "CreateDefence", "Session", new { id = Model.Dissertation.Id }, null)
    }
    @if (Model.CanAddReplies)
    {
        @Html.ActionLink("Добавить отзыв", "Create", "Reply", new { id = Model.Dissertation.Id }, null)
    }
</div>

UD_Granit/Views/Dissertation/Index.cshtml
@model UD_Granit.ViewModels.Dissertation.Index
@using UD_Granit.Helpers

@{
    ViewBag.Title = "Просмотр диссертаций";
}

<h2>@ViewBag.Title</h2>
<p>На этой странице Вы можете просмотреть список диссертаций, которые уже защищены, или будут защищены в ближайшее время. Для фильтрации полученной информации можно использовать поля определённых критериев поиска, которые расположены ниже.</p>

@if ((Model.Dissertations.Count > 0) || Model.SearchHaveResults)
{
    <h3>Поиск</h3>
    <p>Вы можете найти необходимую диссертацию при помощи текстового поля ниже. Введите заголовок диссертации или его часть в текстовое поле и нажмите на кнопку "Поиск".</p>
    using (Html.BeginForm("Index", "Dissertation", FormMethod.Get))
    {
    <div>
        @Html.TextBox("search", @Model.SearchString)
        <button>Поиск</button>
        @if(Model.SearchHaveResults){
            @Html.ActionLink("Очистить результаты поиска", "Index", "Dissertation")
        }
    </div>
    }
}

@if (Model.SearchHaveResults)
{
    <h3>Отображене результатов поиска по запросу "@(Model.SearchString)":</h3>
}

@if (Model.Dissertations.Count > 0)
{
    <h3>Список диссертаций</h3>
    <table>
        <thead>
            <tr>
                <td>Заголовок</td>
                <td>Тип</td>
                <td>Специальность</td>
                <td>Соискатель</td>
                <td>Детали</td>
            </tr>
        </thead>
        <tbody>
            @foreach (UD_Granit.Models.Dissertation currentDissertation in Model.Dissertations)
            {
                <tr>
                    <td>@currentDissertation.Title</td>
                    <td>@currentDissertation.Type.ToDescription()</td>
                    <td>@currentDissertation.Speciality.GetFullName()</td>
                    <td>@currentDissertation.Applicant.GetFullName()</td>
                    <td>@Html.ActionLink("Подробности", "Details", new { id = currentDissertation.Id }, null)</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <div class="error">Нет ни одной записи о диссертации.</div>
}