UD_Granit/Controllers/CouncilController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UD_Granit.Models;
using UD_Granit.Helpers;
using System.Web.Mvc.Html;
using System.Data.SqlClient;

namespace UD_Granit.Controllers
{
    // Управляет логикой по работе с информацией о диссертационном совете
    public class CouncilController : Controller
    {
        private DataContext db = new DataContext();

        // Показывает информацию о диссертационном совете
        // GET: /Council/

        public ActionResult Index()
        {
            UD_Granit.ViewModels.Council.Index viewModel = new ViewModels.Council.Index();

            viewModel.HaveInformation = (db.Council.Count() > 0);
            if (viewModel.HaveInformation)
                viewModel.Council = db.Council.First();
            viewModel.CanControl = RightsManager.Council.Edit(Session.GetUser());

            return View(viewModel);
        }

        // Показывает форму редактирования информации о диссертационном совете
        // GET: /Council/Edit

        public ActionResult Edit()
        {
            User currentUser = Session.GetUser();

            if (currentUser == null)
                throw new HttpException(404, "Not found");

            if (!RightsManager.Council.Edit(currentUser))
                throw new HttpException(404, "Not found");

            var chairman = db.Members.Where(m => (m.Position == MemberPosition.Chairman)).FirstOrDefault();
            var viceCharman = db.Members.Where(m => (m.Position == MemberPosition.ViceChairman)).FirstOrDefault();
            var secretary = db.Members.Where(m => (m.Position == MemberPosition.Secretary)).FirstOrDefault();

            UD_Granit.ViewModels.Council.Edit viewModel = new ViewModels.Council.Edit();

            if (db.Council.Count() > 0)
                viewModel.Council = db.Council.First();
            viewModel.CanDefineChairman = RightsManager.Council.ChangeChairman(currentUser);
            viewModel.CanDefineRoles = (db.Members.Count() >= 3);
            viewModel.Chairman = (chairman != null) ? chairman.Id : 0;
            viewModel.ViceChairman = (viceCharman != null) ? viceCharman.Id : 0;
            viewModel.Secretary = (secretary != null) ? secretary.Id : 0;

            viewModel.Members = new List<SelectListItem>();
            viewModel.Members.Add(new SelectListItem() { Text = "== Выберите члена совета из списка ==", Value = "0" });
            foreach (var currentMember in db.Members)
                viewModel.Members.Add(new SelectListItem() { Text = currentMember.GetFullName(), Value = currentMember.Id.ToString() });

            
            return View(viewModel);
        }

        // Редактирует информацию о диссертационном совете
        // POST: /Council/Edit

        [HttpPost]
        public ActionResult Edit(UD_Granit.ViewModels.Council.Edit viewModel)
        {
            User currentUser = Session.GetUser();

            if (currentUser == null)
                throw new HttpException(404, "Not found");

            if (!RightsManager.Council.Edit(currentUser))
                throw new HttpException(404, "Not found");

            try
            {
                viewModel.CanDefineRoles = (db.Members.Count() >= 3);
                viewModel.CanDefineChairman = RightsManager.Council.ChangeChairman(currentUser);

                viewModel.Chairman = (viewModel.CanDefineChairman) ? viewModel.Chairman : db.Members.Where(m => m.Position == MemberPosition.Chairman).FirstOrDefault().Id;

                if(((viewModel.Chairman == viewModel.ViceChairman) && (viewModel.Chairman != 0)) ||
                    ((viewModel.Chairman == viewModel.Secretary) && (viewModel.Chairman != 0)) ||
                    ((viewModel.Secretary == viewModel.ViceChairman) && (viewModel.Secretary != 0)))
                {
                    throw new Exception("Член совета не может иметь две роли одновременно. Пожалуйста, измените свой выбор.");
                }

                // Удаление старых руководителей
                var chairman = (viewModel.CanDefineChairman) ? db.Members.Where(m => (m.Position == MemberPosition.Chairman)).FirstOrDefault() : null;
                var viceCharman = db.Members.Where(m => (m.Position == MemberPosition.ViceChairman)).FirstOrDefault();
                var secretary = db.Members.Where(m => (m.Position == MemberPosition.Secretary)).FirstOrDefault();

                if ((chairman != null) && (viewModel.CanDefineChairman))
                    chairman.Position = MemberPosition.Member;
                if (viceCharman != null)
                    viceCharman.Position = MemberPosition.Member;
                if (secretary != null)
                    secretary.Position = MemberPosition.Member;

                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                db.Configuration.ValidateOnSaveEnabled = true;

                // Добавление новых руководителей
                chairman = (viewModel.CanDefineChairman) ? db.Members.Find(viewModel.Chairman) : null;
                viceCharman = db.Members.Find(viewModel.ViceChairman);
                secretary = db.Members.Find(viewModel.Secretary);

                if ((chairman != null) && (viewModel.CanDefineChairman))
                    chairman.Position = MemberPosition.Chairman;
                if (viceCharman != null)
                    viceCharman.Position = MemberPosition.ViceChairman;
                if (secretary != null)
                    secretary.Position = MemberPosition.Secretary;

                db.Configuration.ValidateOnSaveEnabled = false;
                db.SaveChanges();
                db.Configuration.ValidateOnSaveEnabled = true;


                if (currentUser is Member)
                    Session.SetUser(db.Members.Find(currentUser.Id));

                if (db.Council.Count() == 0)
                {
                    db.Council.Add(viewModel.Council);
                }
                else
                {
                    viewModel.Council.Id = 1;
                    db.Entry(viewModel.Council).State = System.Data.Entity.EntityState.Modified;
                }
                db.SaveChanges();
                HttpContext.Application["Name"] = viewModel.Council.Number;

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                viewModel.Members = new List<SelectListItem>();
                viewModel.Members.Add(new SelectListItem() { Text = "== Выберите члена совета из списка ==", Value = "0" });
                foreach (var currentMember in db.Members)
                    viewModel.Members.Add(new SelectListItem() { Text = currentMember.GetFullName(), Value = currentMember.Id.ToString() });

                ViewData.NotificationAdd(new NotificationManager.Notify() { Type = NotificationManager.Notify.NotifyType.Error, Message = ex.Message });
                return View(viewModel);
            }
        }

        // Показывает членов диссертационного совета
        // GET: /Council/Members

        public ActionResult Members(string filter)
        {
            UD_Granit.ViewModels.Council.Members viewModel = new ViewModels.Council.Members();

            if (filter == null)
            {
                var q = from m in db.Members orderby m.Position descending select m;
                List<UD_Granit.ViewModels.Council.MemberView> memberList = new List<ViewModels.Council.MemberView>();
                foreach (Member m in q)
                {
                    memberList.Add(new UD_Granit.ViewModels.Council.MemberView() { Name = m.GetFullName(), Degree = m.Degree, Position = m.Position.ToDescription(), Speciality = m.Speciality.GetFullName(), Id = m.Id });
                }

                viewModel.CouncilMembers = memberList;
            }
            else
            {
                switch (filter)
                {
                    case "speciality":
                        var specialities = db.Specialities;
                        if (specialities != null)
                        {
                            viewModel.FilteredMembers = new Dictionary<string, IEnumerable<ViewModels.Council.MemberView>>();
                            foreach (var speciality in specialities)
                            {
                                var members = db.Members.Where(m => (m.Speciality.Number == speciality.Number));
                                if (members.Count() > 0)
                                {
                                    List<UD_Granit.ViewModels.Council.MemberView> memberList = new List<ViewModels.Council.MemberView>();
                                    foreach (Member m in members)
                                    {
                                        memberList.Add(new UD_Granit.ViewModels.Council.MemberView() { Name = m.GetFullName(), Degree = m.Degree, Position = m.Position.ToDescription(), Speciality = m.Speciality.GetFullName(), Id = m.Id });
                                    }
                                    viewModel.FilteredMembers.Add(speciality.GetFullName(), memberList);
                                }
                            }
                        }
                        break;
                    case "scienceBranch":
                        var branches = db.Database.SqlQuery<string>("GetScienceBranches");
                        if (branches != null)
                        {
                            viewModel.FilteredMembers = new Dictionary<string, IEnumerable<ViewModels.Council.MemberView>>();
                            foreach (var scienceBranch in branches)
                            {
                                var members = db.Database.SqlQuery<Member>("GetMembersByScienceBranch @Branch", new SqlParameter("Branch", scienceBranch));

UD_Granit/Controllers/SpecialityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UD_Granit.Helpers;
using UD_Granit.Models;

namespace UD_Granit.Controllers
{
    // Управляет логикой по работе со специальностями
    public class SpecialityController : Controller
    {
        private DataContext db = new DataContext();

        // Показывает специальности
        // GET: /Speciality/[1]

        public ActionResult Index(int? err)
        {
            UD_Granit.ViewModels.Speciality.Index viewModel = new ViewModels.Speciality.Index();
            viewModel.Specialities = db.Specialities;
            viewModel.CanControl = RightsManager.Speciality.Control(Session.GetUser());

            if (err.HasValue && (err.Value == 1))
                ViewData.NotificationAdd(new NotificationManager.Notify() { Type = NotificationManager.Notify.NotifyType.Error, Message = "Специальность связана с диссертациями и (или) членами совета. Удаление невозможно." });

            return View(viewModel);
        }

        // Показывает форму добавления специальности
        // GET: /Speciality/Create

        public ActionResult Create()
        {
            if (!RightsManager.Speciality.Control(Session.GetUser()))
                throw new HttpException(404, "Not found");

            return View();
        }

        // Создаёт специальность
        // POST: /Speciality/Create

        [HttpPost]
        public ActionResult Create(UD_Granit.ViewModels.Speciality.Create viewModel)
        {
            if (!RightsManager.Speciality.Control(Session.GetUser()))
                throw new HttpException(404, "Not found");

            try
            {
                if (ModelState.IsValid)
                {
                    if (db.Specialities.Find(viewModel.Speciality.Number) == null)
                    {
                        db.Specialities.Add(viewModel.Speciality);
                        db.SaveChanges();
                    }
                    else
                    {
                        ViewData.NotificationAdd(new NotificationManager.Notify() { Message = "Специальность с таким номером уже существует.", Type = NotificationManager.Notify.NotifyType.Error });
                        return View(viewModel);
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewData.NotificationAdd(new NotificationManager.Notify() { Message = ex.Message, Type = NotificationManager.Notify.NotifyType.Error });
                return View();
            }
        }

        // Показывает форму изменения информации о специальности
        // GET: /Speciality/Edit/5

        public ActionResult Edit(string id)
        {
            if (RightsManager.Speciality.Control(Session.GetUser()))
            {
                UD_Granit.ViewModels.Speciality.Edit viewModel = new ViewModels.Speciality.Edit();
                viewModel.Speciality = db.Specialities.Find(id);
                if (viewModel.Speciality != null)
                    return View(viewModel);
            }
            throw new HttpException(404, "Not found");
        }

        // Редактирует специальность
        // POST: /Speciality/Edit/5

        [HttpPost]
        public ActionResult Edit(UD_Granit.ViewModels.Speciality.Edit viewModel)
        {
            if (!RightsManager.Speciality.Control(Session.GetUser()))
                throw new HttpException(404, "Not found");

            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry<Speciality>(viewModel.Speciality).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewData.NotificationAdd(new NotificationManager.Notify() { Message = ex.Message, Type = NotificationManager.Notify.NotifyType.Error });
                return View();
            }
        }

        // Удаляет специальность
        // GET: /Speciality/Delete/5

        public ActionResult Delete(string id)
        {
            if (!RightsManager.Speciality.Control(Session.GetUser()))
                throw new HttpException(404, "Not found");

            Speciality currentSpeciality = db.Specialities.Find(id);
            int err;

            if(currentSpeciality == null)
                throw new HttpException(404, "Not found");

            if ((db.Members.Where(m => m.Speciality.Number == id).Count() == 0) && (db.Dissertations.Where(d => d.Speciality.Number == id).Count() == 0))
            {
                err = 0;
                db.Specialities.Remove(currentSpeciality);
                db.SaveChanges();
            }
            else
            {
                err = 1;
            }

            return RedirectToAction("Index", new { err = err });
        }
    }
}

UD_Granit/Controllers/StyleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UD_Granit.Controllers
{
    // Управляет логикой по работе со стилями
    public class StyleController : Controller
    {
        // Задаёт обычный стиль отображения
        // GET: /Style/Basic

        public ActionResult Basic()
        {
            Session.Remove("Lite");
            if (Request.UrlReferrer != null)
                return Redirect(Request.UrlReferrer.OriginalString);
            else
                return Redirect("/");
        }

        // Задаёт упрощённый стиль отображения
        // GET: /Style/Lite

        public ActionResult Lite()
        {
            Session["Lite"] = String.Empty;
            if (Request.UrlReferrer != null)
                return Redirect(Request.UrlReferrer.OriginalString);
            else
                return Redirect("/");
        }
    }
}

UD_Granit/Views/Shared/Error404.cshtml
@{
    ViewBag.Title = "Ошибка";
}

<h2>Страница не найдена</h2>
<div class="PageImage">
    <img src="/Content/error.png" alt="" />
</div>
<p>Присносим свои извинения, однако страница, которую Вы пытаетесь открыть, не существует на сервере, либо у Вас нет прав на её просмотр.</p>
<p>Попробуйте перейти на <a href="/">главную страницу сайта</a> и заново повторить попытку доступа на эту страницу. Также можете попытаться перейти <a href="javascript:history.back(1)">назад</a> в истории посещений.</p>
<p>Если Вам кажется, что такой ошибки на этой странице быть не должно, обратитесь к администратору системы.</p>

UD_Granit/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/css/basic.css")
</head>
<body>
    <div class="page-wrap">
        <header>
            @Html.Partial("_PartialHeader")
        </header>
        <div id="MainWrapper">
            <aside>
                @Html.Partial("_PartialAside")
            </aside>
            <article>
                @Html.Partial("_PartialNotification")
                @RenderBody()
            </article>
            <div class="cb"></div>
        </div>
    </div>
    <footer>
        <div id="FooterWrapper">
            @Html.Partial("_PartialFooter")
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>

UD_Granit/Views/Shared/LayoutLite.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/css/lite.css")
</head>
<body>
    <div id="MainWrapper">
        <header>
            @Html.Partial("_PartialHeader")
        </header>
        <aside>
            @Html.Partial("_PartialAside")
        </aside>
        <article>
            @Html.Partial("_PartialNotification")
            @RenderBody()
        </article>
        <div class="cb"></div>
        <footer>
            @Html.Partial("_PartialFooter")
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>

UD_Granit/Views/Shared/_AsideLogin.cshtml
@using UD_Granit.Helpers

<div class="section">
    <h3>Авторизация</h3>
    @if (Session["User"] == null)
    {
        <p>Вы не авторизованы в системе. Чтобы выполнить вход, пожалуйста, введите свои учётные данные на <a href="@Url.Action("Login", "Account")">специальной странице</a>.</p>
    }
    else
    {
        <ul class="menu">
            <li>@Html.ActionLink("Информация о пользователе", "Details", "Account")</li>
            <li>@Html.ActionLink("Выход", "Logout", "Account")</li>
        </ul>
    }
</div>

UD_Granit/Views/Shared/_AsideMainMenu.cshtml
<div class="section">
    <h3>Меню системы</h3>
    <ul class="menu">
        <li>@Html.ActionLink("Главная страница", "Index", "Home")</li>
        <li>@Html.ActionLink("Заседания", "Index", "Session")</li>
        <li>@Html.ActionLink("Просмотр диссертаций", "Index", "Dissertation")</li>
        <li>@Html.ActionLink("Информация о совете", "Index", "Council")</li>
        <li>@Html.ActionLink("Состав совета", "Members", "Council")</li>
        <li>@Html.ActionLink("Специальности", "Index", "Speciality")</li>
    </ul>
</div>

UD_Granit/Views/Shared/_AsideRegister.cshtml
@if (Session["User"] == null)
{
    <div class="section">
        <h3>Стать соискателем</h3>
        <p>Хотите зарегистрироваться как соискатель? Вы можете это сделать на <a href="@Url.Action("Register", "Account")">специальной странице</a>.</p>
    </div>
}

UD_Granit/Views/Shared/_AsideUserMenu.cshtml
@using UD_Granit.Helpers
@if (Session.GetUser() != null)
{
    <div class="section">
        <h3>Меню пользователя</h3>

        <ul class="menu">
            @if (Session.GetUser() is UD_Granit.Models.Applicant)
            {
                <li>@Html.ActionLink("Диссертация", "My", "Dissertation")</li>
                <li>@Html.ActionLink("Заседания", "My", "Session")</li>
            }

            @if ((Session.GetUserPosition() == UD_Granit.Models.MemberPosition.Member) ||
            (Session.GetUserPosition() == UD_Granit.Models.MemberPosition.ViceChairman))
            {
                <li>@Html.ActionLink("Заседания", "My", "Session")</li>
            }
            @if (Session.GetUserPosition() == UD_Granit.Models.MemberPosition.Secretary)
            {
                <li>@Html.ActionLink("Зарегистрировать пользователя", "Register", "Account")</li>
                <li>@Html.ActionLink("Заседания", "My", "Session")</li>
            }
            @if (Session.GetUserPosition() == UD_Granit.Models.MemberPosition.Chairman)
            {
                <li>@Html.ActionLink("Пользователи", "All", "Account")</li>
                <li>@Html.ActionLink("Заседания", "My", "Session")</li>
                <li>@Html.ActionLink("Специальности", "Index", "Speciality")</li>
            }
            @if (Session.GetUser() is UD_Granit.Models.Administrator)
            {
                <li>@Html.ActionLink("Пользователи", "All", "Account")</li>
                <li>@Html.ActionLink("Специальности", "Index", "Speciality")</li>
            }
        </ul>
    </div>
}

UD_Granit/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css/basic/main.css")
    <script src="@Url.Content("~/Scripts/jquery-2.0.3.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>
<body>
    <header>
        @Html.Partial("_PartialHeader")
    </header>
    <div id="MainWrapper">
        <aside>
            @Html.Partial("_PartialAside")
        </aside>
        <article>
            @RenderBody()
        </article>
        <div class="cb"></div>
    </div>
    <footer>
        <div id="FooterWrapper">
            @Html.Partial("_PartialFooter")
        </div>
    </footer>
</body>
</html>

UD_Granit/Views/Shared/_LayoutLite.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css/lite/main.css")
</head>
<body>
    @RenderBody()
</body>
</html>

UD_Granit/Views/Shared/_PartialAside.cshtml
@Html.Partial("_AsideMainMenu")
@Html.Partial("_AsideUserMenu")

@Html.Partial("_AsideLogin")
@Html.Partial("_AsideRegister")

UD_Granit/Views/Shared/_PartialFooter.cshtml
<div id="FooterLinks">
    <p>@Html.ActionLink("О системе", "About", "Home")</p>
    <p>@Html.ActionLink("Статистика", "Statistics", "Home")</p>
</div>

<p>&copy;&nbsp;2013 — Моисеев В.В. Все права защищены действующим законодательством России.</p>
<p>Любое копирование материалов с данного сайта разрешается при условии размещения ссылки на первоисточник.</p>

UD_Granit/Views/Shared/_PartialHeader.cshtml
<div id="StyleChanger">
    Стиль отображения: @Html.ActionLink("Обычный", "Basic", "Style") | @Html.ActionLink("Упрощённый", "Lite", "Style")
</div>

<hgroup>
    <div class="logo"></div>
    <h1>@HttpContext.Current.Application["Name"]</h1>
    <h4>Автоматизированная система управления работой диссертационного совета</h4>
</hgroup>

UD_Granit/Views/Shared/_PartialNotification.cshtml
@using UD_Granit.Helpers

@if (Html.Notifications() != null)
{
    NotificationManager notificationManager = Html.Notifications();
    if (notificationManager.Count > 0)
    {
        foreach (NotificationManager.Notify notify in notificationManager.Notifies)
        {
            <div class="@notify.Class">@Html.Raw(notify.Message)</div>
        }
    }
}