UD_Granit/Models/Session/Session.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace UD_Granit.Models
{
    public class Session
    {
        [Key]
        public int Id { set; get; }

        [Required]
        [Display(Name = "Дата проведения заседания")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime Date { set; get; }

        [Required]
        [Display(Name = "Заседание состоялось")]
        public bool Was { set; get; }

        public virtual Dissertation Dissertation { set; get; }
        public virtual ICollection<Member> Members { set; get; }
    }
}

UD_Granit/Models/Session/SessionConsideration.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UD_Granit.Models
{
    public class SessionConsideration : Session
    {
        [Display(Name="Результат заседания")]
        public string Result { set; get; }
    }
}

UD_Granit/Models/Session/SessionDefence.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UD_Granit.Models
{
    public class SessionDefence : Session
    {
        [Display(Name = "Итог защиты")]
        public bool Result { set; get; }

        [Display(Name = "Число голосов за защиту")]
        public int Vote_Result { set; get; }

        [Display(Name = "Запись защиты")]
        public string File_Recording { set; get; }

        [Display(Name = "Степень достоверности результатов")]
        public string Reliability { set; get; }

        [Display(Name = "Научная новизна результатов")]
        public string Novelty { set; get; }

        [Display(Name = "Значимость работы")]
        public string Significance { set; get; }
    }
}

UD_Granit/Models/Sessions.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UD_Granit.Models
{
    public class Session
    {
        [Key]
        public int Id { set; get; }

        public DateTime Date { set; get; }
        public bool Was { set; get; }
        //идентификатор диссертации
    }

    public class SessionСonsideration : Session
    {
        public string Result { set; get; }
    }

    public class SessionDefence : Session
    {
        public bool Result { set; get; }
        public int Vote_Result { set; get; }
        public byte[] Recording { set; get; }
        public string Reliability { set; get; }
        public string Novelty { set; get; }
        public string Significance { set; get; }
    }
}

UD_Granit/ViewModels/Account/Delete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Account
{
    public class Delete
    {
        public int Id { set; get; }
        public string Name { set; get; }
        public string Referer { set; get; }
        public bool CanDelete { set; get; }
    }
}

UD_Granit/ViewModels/Account/Details.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Account
{
    public class ApplicantViewItem
    {
        [Display(Name = "Город")]
        public string City { set; get; }

        [Display(Name = "Организация")]
        public string Organization { set; get; }

        [Display(Name = "Подразделение")]
        public string Organization_Depatment { set; get; }
    }

    public class MemberViewItem
    {
        [Display(Name = "Должность")]
        public string Position { set; get; }

        [Display(Name = "Специальность")]
        public UD_Granit.Models.Speciality Speciality { set; get; }
    }

    public class Details
    {
        public int User_Id { set; get; }

        [Display(Name = "Полное имя")]
        public string FullName { set; get; }

        [Display(Name = "Роль")]
        public string Role { set; get; }

        public ApplicantViewItem ApplicantView { set; get; }
        public MemberViewItem MemberView { set; get; }

        public bool CanControl { set; get; }
    }
}

UD_Granit/ViewModels/Dissertation/Create.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UD_Granit.ViewModels.Dissertation
{
    public class Create
    {
        public UD_Granit.Models.Dissertation Dissertation { set; get; }

        [Required]
        [Display(Name = "Файл с авторефератом")]
        public HttpPostedFileBase File_Abstract { set; get; }

        [Required]
        [Display(Name = "Файл с текстом диссертации")]
        public HttpPostedFileBase File_Text { set; get; }

        [Required]
        [Display(Name = "Файл с заключением ведущей организации")]
        public HttpPostedFileBase File_Summary { set; get; }

        [Required]
        [Display(Name = "Специальность")]
        public string Speciality { set; get; }
    }
}

UD_Granit/ViewModels/Dissertation/Delete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Dissertation
{
    public class Delete
    {
        public int Id { set; get; }
        public string Title { set; get; }
        public bool CanDelete { set; get; }
    }
}

UD_Granit/ViewModels/Dissertation/Details.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Dissertation
{
    public class Details
    {
        public UD_Granit.Models.Dissertation Dissertation { set; get; }

        public bool CanEdit { set; get; }
        public bool CanCreateSession { set; get; }
        public bool CanAddReplies { set; get; }
        public bool CanEditReplies { set; get; }
    }
}

UD_Granit/ViewModels/Reply/Create.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Reply
{
    public class Create
    {
        [Required]
        public int Dissertation_Id { set; get; }

        [Required]
        public Models.Reply Reply { set; get; }
    }
}

UD_Granit/ViewModels/Session/Create.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UD_Granit.ViewModels.Session
{
    public class Create
    {
        public int Dissertation_Id { set; get; }
        public string Dissertation_Title { set; get; }

        public UD_Granit.Models.Session Session { set; get; }
        public string SessionType { set; get; }

        public List<SelectListItem> MemberList { set; get; }
        public int MembersCount { set; get; }
    }
}

UD_Granit/ViewModels/Session/CreateConsideration.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace UD_Granit.ViewModels.Session
{
    public class CreateConsideration
    {
        public int Dissertation_Id { set; get; }
        public string Dissertation_Title { set; get; }

        public UD_Granit.Models.SessionСonsideration Session { set; get; }

        public List<SelectListItem> MemberList { set; get; }
        public int MembersCount { set; get; }
    }
}

UD_Granit/ViewModels/Session/Delete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace UD_Granit.ViewModels.Session
{
    public class Delete
    {
        public int Id { set; get; }
        public string Title { set; get; }
        public DateTime Date { set; get; }
    }
}

UD_Granit/Controllers/SessionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UD_Granit.Models;
using UD_Granit.Helpers;
using System.IO;

namespace UD_Granit.Controllers
{
    // Управляет логикой по работе с сессиями
    public class SessionController : Controller
    {
        private DataContext db = new DataContext();

        // Показывает список доступных сессий
        // GET: /Session/

        public ActionResult Index()
        {
            User currentUser = Session.GetUser();

            var prevSessions = db.Sessions.Where(s => (s.Was)).OrderByDescending(s => s.Date);
            var nextSessions = db.Sessions.Where(s => (!s.Was)).OrderBy(s => s.Date);

            List<Session> SessionsWas = new List<Session>();
            List<Session> SessionsWill = new List<Session>();

            foreach (Session currentSession in prevSessions)
                if (RightsManager.Dissertation.Show(currentUser, currentSession.Dissertation))
                    SessionsWas.Add(currentSession);

            foreach (Session currentSession in nextSessions)
                if (RightsManager.Dissertation.Show(currentUser, currentSession.Dissertation))
                    SessionsWill.Add(currentSession);

            ViewModels.Session.Index viewModel = new ViewModels.Session.Index();
            viewModel.SessionsWas = SessionsWas;
            viewModel.SessionsWill = SessionsWill;
            return View(viewModel);
        }

        // Показывает форму создания заседания по рассмотрению диссертации
        // GET: /Session/CreateConsideration

        public ActionResult CreateConsideration(int id)
        {
            UD_Granit.ViewModels.Session.Create viewModel = new ViewModels.Session.Create();

            Dissertation currentDissertation = db.Dissertations.Find(id);
            if (currentDissertation == null)
                throw new HttpException(404, "Not found");

            viewModel.SessionType = "Consideration";
            viewModel.Dissertation_Id = id;
            viewModel.Dissertation_Title = currentDissertation.Title;
            viewModel.MemberList = new List<SelectListItem>();

            viewModel.MemberList.Add(new SelectListItem() { Text = "== Выберите члена совета из списка ==", Value = "-1", Selected = true });
            foreach (var member in db.Members)
            {
                viewModel.MemberList.Add(new SelectListItem() { Text = member.GetFullName(), Value = member.Id.ToString() });
            }

            return View("Create", viewModel);
        }

        // Показывает форму создания заседания по защите
        // GET: /Session/CreateDefence

        public ActionResult CreateDefence(int id)
        {
            if (!RightsManager.Session.Create(Session.GetUser()))
                throw new HttpException(404, "Not found");

            UD_Granit.ViewModels.Session.Create viewModel = new ViewModels.Session.Create();

            Dissertation currentDissertation = db.Dissertations.Find(id);
            if (currentDissertation == null)
                throw new HttpException(404, "Not found");

            viewModel.SessionType = "Defence";
            viewModel.Dissertation_Id = id;
            viewModel.Dissertation_Title = currentDissertation.Title;
            viewModel.MemberList = new List<SelectListItem>();

            viewModel.MemberList.Add(new SelectListItem() { Text = "== Выберите члена совета из списка ==", Value = "-1", Selected = true });
            foreach (var member in db.Members)
            {
                viewModel.MemberList.Add(new SelectListItem() { Text = member.GetFullName(), Value = member.Id.ToString() });
            }

            return View("Create", viewModel);
        }

        // Создаёт заседание
        // POST: /Session/Create

        [HttpPost]
        public ActionResult Create(UD_Granit.ViewModels.Session.Create viewModel)
        {
            if (!RightsManager.Session.Create(Session.GetUser()))
                throw new HttpException(404, "Not found");

            Dissertation currentDissertation = db.Dissertations.Find(viewModel.Dissertation_Id);
            if (currentDissertation == null)
                throw new HttpException(404, "Not found");

            try
            {
                Session currentSession = viewModel.Session;
                currentSession.Dissertation = db.Dissertations.Find(viewModel.Dissertation_Id);
                currentSession.Was = false;

                if (viewModel.MembersCount > 0)
                {
                    currentSession.Members = new List<Member>();
                    for (int i = 0; i < viewModel.MembersCount; i++)
                    {
                        try
                        {
                            Member currentMember = db.Members.Find(Convert.ToInt32(Request.Form[string.Format("Member{0}", i)]));
                            if (currentMember != null)
                                currentSession.Members.Add(currentMember);
                        }
                        catch { }
                    }
                }

                switch (viewModel.SessionType)
                {
                    case "Consideration":
                        currentSession = new SessionConsideration() { Dissertation = currentSession.Dissertation, Date = currentSession.Date, Was = currentSession.Was, Members = currentSession.Members };
                        db.SessionsСonsideration.Add(currentSession as SessionConsideration);
                        break;
                    case "Defence":
                        currentSession = new SessionDefence() { Dissertation = currentSession.Dissertation, Date = currentSession.Date, Was = currentSession.Was, Members = currentSession.Members };
                        db.SessionsDefence.Add(currentSession as SessionDefence);
                        break;
                }
                db.SaveChanges();

                return RedirectToAction("Details", new { id = currentSession.Id });
            }
            catch (Exception ex)
            {
                viewModel.Dissertation_Title = currentDissertation.Title;
                viewModel.MemberList = new List<SelectListItem>();

                viewModel.MemberList.Add(new SelectListItem() { Text = "== Выберите члена совета из списка ==", Value = "-1", Selected = true });
                foreach (var member in db.Members)
                {
                    viewModel.MemberList.Add(new SelectListItem() { Text = member.GetFullName(), Value = member.Id.ToString() });
                }

                ViewData.NotificationAdd(new NotificationManager.Notify() { Type = NotificationManager.Notify.NotifyType.Error, Message = ex.Message });
                return View(viewModel);
            }
        }

        // Показывает заседания, к которым прикреплён пользователь
        // GET: /Session/My

        public ActionResult My()
        {
            User currentUser = Session.GetUser() as User;
            if (currentUser == null)
                throw new HttpException(404, "Not found");

            if (!(currentUser is Member) && !(currentUser is Applicant))
                throw new HttpException(404, "Not found");

            UD_Granit.ViewModels.Session.My viewModel = new ViewModels.Session.My();
            if (currentUser is Member)
            {
                viewModel.ViewType = ViewModels.Session.SessionViewType.MemberView;
                viewModel.Sessions = db.Members.Find(currentUser.Id).Sessions.OrderBy(s => s.Was).ThenByDescending(s => s.Date);
            }
            if (currentUser is Applicant)
            {
                viewModel.ViewType = ViewModels.Session.SessionViewType.ApplicantView;
                Dissertation currentDissertation = db.Dissertations.Find(currentUser.Id);
                viewModel.Sessions = (currentDissertation != null) ? db.Dissertations.Find(currentUser.Id).Sessions.OrderBy(s => s.Was).ThenByDescending(s => s.Date) : null;
            }
            return View(viewModel);
        }

        // Показыает подробности заседания
        // GET: /Session/Details/5

        public ActionResult Details(int id)
        {
            User currentUser = Session.GetUser();
            Session currentSession = db.Sessions.Find(id);

            if (currentSession == null)
                throw new HttpException(404, "Not found");

            if (!RightsManager.Dissertation.Show(currentUser, currentSession.Dissertation))
                throw new HttpException(404, "Not found");

            UD_Granit.ViewModels.Session.Details viewModel = new ViewModels.Session.Details();
            viewModel.Session = currentSession;
            viewModel.CanControl = RightsManager.Session.Edit(currentUser);
            return View(viewModel);
        }

        // Показывает форму заполнения результата заседания
        // GET: /Session/Result/5

        public ActionResult Result(int id)
        {
            User currentUser = Session.GetUser() as User;
            Session currentSession = db.Sessions.Find(id);

            if (!RightsManager.Session.Edit(currentUser))
                throw new HttpException(404, "Not found");

            if (currentSession is SessionConsideration)
            {
                ViewModels.Session.ResultConsideration viewModel = new ViewModels.Session.ResultConsideration();

                viewModel.DissertationTitle = currentSession.Dissertation.Title;
                viewModel.Id = currentSession.Id;
                viewModel.Date = currentSession.Date;

                return View("ResultConsideration", viewModel);
            }
            if (currentSession is SessionDefence)
            {
                ViewModels.Session.ResultDefence viewModel = new ViewModels.Session.ResultDefence();

                viewModel.DissertationTitle = currentSession.Dissertation.Title;
                viewModel.Id = currentSession.Id;

UD_Granit/Views/Session/Create.cshtml
@model UD_Granit.ViewModels.Session.Create

@{
    ViewBag.Title = "Новое заседание";
}

<h2>Создание записи о заседании</h2>

@using (Html.BeginForm("Create", "Session"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Dissertation_Id)
    @Html.HiddenFor(model => model.MembersCount)
    @Html.HiddenFor(model => model.SessionType)

    <fieldset>
        <legend>Основная информация</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Session.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Session.Date)
            @Html.ValidationMessageFor(model => model.Session.Date)
        </div>
    </fieldset>
    
    <fieldset>
        <legend>Информация о прикреплённых членах совета</legend>

        <div id="MembersContainer">
            @for (int i = 0; i < Model.MemberList.Count; i++)
            {
                <div id="Member@(i)">@Html.DropDownList("Member" + i, Model.MemberList)</div>
            }
        </div>
        <div id="MembersControl">
            <a id="AddMemberButton" href="#">Добавить члена совета</a> | 
            <a id="DeleteMemberButton" href="#">Убрать члена совета</a>
        </div>
    </fieldset>
    
    <div class="control">
        <button>Создать заседание</button>
    </div>
}

@section scripts {
	<script>
		$(function () {
			$("#Session_Date").appendDtpicker({ locale: "ru", closeOnSelected: true, firstDayOfWeek: 1 });
			HideMembers();

			$('#AddMemberButton').click(AddMember);
			$('#DeleteMemberButton').click(DeleteMember);
		});

		var membersCount = @(Model.MemberList.Count - 1);
		var membersShowed = 0;

		AddMember = function() {
			if(membersShowed < membersCount) {
				$('#Member' + membersShowed.toString()).show();
				++membersShowed;
				$('#MembersCount').val(membersShowed);
			}
		}

		DeleteMember = function() {
			if(membersShowed > 0) {
				$('#Member' + (--membersShowed).toString()).hide();
				$('#MembersCount').val(membersShowed);
			}
		}

		HideMembers = function () {
			$('#MembersContainer').children().hide();
			$('#MembersCount').val(membersShowed);
		}
	</script>
}

UD_Granit/Views/Session/CreateConsideration.cshtml
@model UD_Granit.ViewModels.Session.CreateConsideration

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Dissertation_Id)
    @Html.HiddenFor(model => model.MembersCount)

    <fieldset>
        <legend>Session</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Session.Date)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Session.Date)
            @Html.ValidationMessageFor(model => model.Session.Date)
        </div>

        <div id="MembersContainer">
            @for (int i = 0; i < Model.MemberList.Count; i++)
            {
                <div id="Member@(i)">@Html.DropDownList("Member" + i, Model.MemberList)</div>
            }
        </div>
        <div id="MembersControl">
            <a id="AddMemberButton" href="#">Добавить члена совета</a> | 
            <a id="DeleteMemberButton" href="#">Убрать члена совета</a>
        </div>

        <div class="control">
            <button>Создать заседание</button>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    $(function () {
        $("#Session_Date").datepicker({ changeYear: true });
        HideMembers();

        $('#AddMemberButton').click(AddMember);
        $('#DeleteMemberButton').click(DeleteMember);
    });

    var membersCount = @(Model.MemberList.Count - 1);
    var membersShowed = 0;

    AddMember = function() {
        if(membersShowed < membersCount) {
            $('#Member' + membersShowed.toString()).show();
            ++membersShowed;
            $('#MembersCount').val(membersShowed);
        }
    }

    DeleteMember = function() {
        if(membersShowed > 0) {
            $('#Member' + (--membersShowed).toString()).hide();
            $('#MembersCount').val(membersShowed);
        }
    }

    HideMembers = function () {
        $('#MembersContainer').children().hide();
        $('#MembersCount').val(membersShowed);
    }
</script>

UD_Granit/Views/Session/Delete.cshtml
@model UD_Granit.ViewModels.Session.Delete

@{
    ViewBag.Title = "Удаление диссертации";
}

<h2>Удаление записи о диссертации</h2>

@using (Html.BeginForm("Delete", "Session"))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)

    <p>Вы действительно хотите удалить запись о заседании, проходившем @Model.Date о диссертации <b>@Model.Title</b>?</p>
    
    <div class="control">
        <button>Да</button>
        @Html.ActionLink("Отмена", "Details", new { Id = Model.Id })
    </div>
}

UD_Granit/Views/Session/Index.cshtml
@model UD_Granit.ViewModels.Session.Index
@using UD_Granit.Helpers

@{
    ViewBag.Title = "Заседание";
}

<h2>Информация о заседаниях</h2>
<p>На этой странице отображаются заседания по рассмотрению и защите диссертаций. Заседания разделены на проведённые и непроведённые.</p>

@if (Model.SessionsWas.Count > 0)
{
    <h3>Проведённые заседания</h3>
    
    <table>
        <thead>
            <tr>
                <td>Название диссертации</td>
                <td>Дата проведения</td>
                <td>Соискатель</td>                
                <td>Подробности</td>
            </tr>
        </thead>
        <tbody>
            @foreach (UD_Granit.Models.Session currentSession in Model.SessionsWas)
            {
                <tr>
                    <td>@Html.ActionLink(currentSession.Dissertation.Title, "Details", "Dissertation", new { id = currentSession.Dissertation.Id }, null)</td>
                    <td>@currentSession.Date</td>
                    <td>@Html.ActionLink(currentSession.Dissertation.Applicant.GetFullName(), "Details", "Account", new { id = currentSession.Dissertation.Applicant.Id }, null)</td>
                    <td>@Html.ActionLink("Подробности", "Details", "Session", new { id = currentSession.Id }, null)</td>
                </tr>
            }
        </tbody>
    </table>
}
@if (Model.SessionsWill.Count > 0)
{
    <h3>Непроведённые заседания</h3>
    
    <table>
        <thead>
            <tr>
                <td>Название диссертации</td>
                <td>Дата проведения</td>
                <td>Соискатель</td>
                <td>Подробности</td>
            </tr>
        </thead>
        <tbody>
            @foreach (UD_Granit.Models.Session currentSession in Model.SessionsWill)
            {
                <tr>
                    <td>@Html.ActionLink(currentSession.Dissertation.Title, "Details", "Dissertation", new { id = currentSession.Dissertation.Id }, null)</td>
                    <td>@currentSession.Date</td>
                    <td>@Html.ActionLink(currentSession.Dissertation.Applicant.GetFullName(), "Details", "Account", new { id = currentSession.Dissertation.Applicant.Id }, null)</td>
                    <td>@Html.ActionLink("Подробности", "Details", "Session", new { id = currentSession.Id }, null)</td>
                </tr>
            }
        </tbody>
    </table>
}
@if ((Model.SessionsWill.Count == 0) && (Model.SessionsWas.Count == 0))
{
    <div class="error">
        Извините, не найдено ни одной записи о заседаниях.
    </div>
}

UD_Granit/Views/Session/My.cshtml
@model UD_Granit.ViewModels.Session.My

@{
    ViewBag.Title = "Заседания";
}

<h2>Прикреплённые заседания</h2>
<p>На этой странице Вы можете видеть заседания, к которым Вы прикреплены. Вы можете просмотреть более детальную информацию, нажав на ссылку "Подробнее" напротив записи о конкретном заседании.</p>

@if ((Model.Sessions != null) && (Model.Sessions.Count() > 0))
{
    <table>
        <thead>
            <tr>
                <td>Тип заседания</td>
                <td>Отметка о проведении</td>
                <td>Дата проведения</td>
                <td>Название дисиертации</td>
                <td>Детали</td>
            </tr>
        </thead>
        <tbody>
            @foreach (UD_Granit.Models.Session currentSession in Model.Sessions)
            {
                <tr>
                    <td>@((currentSession is UD_Granit.Models.SessionConsideration)? "Рассмотрение" : "Защита")</td>
                    <td>@(currentSession.Was ? "Проведено" : "Не проведено")</td>
                    <td>@currentSession.Date</td>
                    <td>@Html.ActionLink(currentSession.Dissertation.Title, "Details", "Dissertation", new { id = currentSession.Dissertation.Id }, null)</td>
                    <td>@Html.ActionLink("Подробнее", "Details", new { id = currentSession.Id })</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    if (Model.ViewType == UD_Granit.ViewModels.Session.SessionViewType.ApplicantView)
    {
    <div class="error">
        Извините, нет ни одного заседания по поводу вашей диссертации.
    </div>
    }
    if (Model.ViewType == UD_Granit.ViewModels.Session.SessionViewType.MemberView)
    {
    <div class="error">
        Извините, Вы не числитесь ни в одном заседании.
    </div>
    }
}

UD_Granit/Views/Session/ResultConsideration.cshtml
@model UD_Granit.ViewModels.Session.ResultConsideration

@{
    ViewBag.Title = "Результат заседания";
}

<h2>Результат заседания по рассмотрению диссертации к защите</h2>
<h3>@Model.DissertationTitle (@Model.Date)</h3>

@using (Html.BeginForm("ResultConsideration", "Session"))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    
    <div class="editor-label">
        @Html.LabelFor(model => model.Result)
    </div>
    <div class="editor-field">
        @Html.TextAreaFor(model => model.Result)<br />
        @Html.ValidationMessageFor(model => model.Result)
    </div>
    
    <div class="control">
        <button>Заполнить результат</button>
        @Html.ActionLink("Отмена", "Details", new { id = Model.Id }, null)
    </div>
}

UD_Granit/Views/Session/ResultDefence.cshtml
@model UD_Granit.ViewModels.Session.ResultDefence

@{
    ViewBag.Title = "Результат заседания";
}

<h2>Результат заседания по защите диссертации</h2>
<h3>@Model.DissertationTitle (@Model.Date)</h3>

@using (Html.BeginForm("ResultDefence", "Session", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    
    <div class="editor-label">
        @Html.LabelFor(model => model.Result)
    </div>
    <div class="editor-field">
        @Html.CheckBoxFor(model => model.Result)
        @Html.ValidationMessageFor(model => model.Result)
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(model => model.Vote_Result)
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.Vote_Result)
        @Html.ValidationMessageFor(model => model.Vote_Result)
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(model => model.Reliability)
    </div>
    <div class="editor-field">
        @Html.TextAreaFor(model => model.Reliability)<br />
        @Html.ValidationMessageFor(model => model.Reliability)
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(model => model.Novelty)
    </div>
    <div class="editor-field">
        @Html.TextAreaFor(model => model.Novelty)<br />
        @Html.ValidationMessageFor(model => model.Novelty)
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(model => model.Significance)
    </div>
    <div class="editor-field">
        @Html.TextAreaFor(model => model.Significance)<br />
        @Html.ValidationMessageFor(model => model.Significance)
    </div>
    
    <div class="editor-label">
        @Html.LabelFor(model => model.File_Recording)
    </div>
    <div class="editor-field">
        @Html.TextBoxFor(model => model.File_Recording, new { type = "file" })
        @Html.ValidationMessageFor(model => model.File_Recording)
    </div>
    
    <div class="control">
        <button>Заполнить результат</button>
        @Html.ActionLink("Отмена", "Details", new { id = Model.Id }, null)
    </div>
}